# Podman Compose Configuration
# Exam Management System
# Version: 1.0.0

version: "3.8"

services:
  # ===========================================
  # MySQL Database
  # ===========================================
  mysql:
    image: docker.io/library/mysql:8.0
    container_name: exam_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${DB_DATABASE:-exam_management}
      MYSQL_USER: ${DB_USERNAME:-exam_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-exam_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    networks:
      - exam_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===========================================
  # Redis Cache
  # ===========================================
  redis:
    image: docker.io/library/redis:7-alpine
    container_name: exam_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - exam_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===========================================
  # Laravel Backend
  # ===========================================
  backend:
    build:
      context: ../../src/backend
      dockerfile: Dockerfile
    container_name: exam_backend
    restart: unless-stopped
    environment:
      APP_NAME: "Exam Management System"
      APP_ENV: ${APP_ENV:-local}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8000}
      
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-exam_management}
      DB_USERNAME: ${DB_USERNAME:-exam_user}
      DB_PASSWORD: ${DB_PASSWORD:-exam_password}
      
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis
    volumes:
      - ../../src/backend:/var/www/html
      - backend_storage:/var/www/html/storage
    ports:
      - "8000:8000"
    networks:
      - exam_network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  # ===========================================
  # Laravel Queue Worker
  # ===========================================
  queue:
    build:
      context: ../../src/backend
      dockerfile: Dockerfile
    container_name: exam_queue
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-exam_management}
      DB_USERNAME: ${DB_USERNAME:-exam_user}
      DB_PASSWORD: ${DB_PASSWORD:-exam_password}
      REDIS_HOST: redis
      QUEUE_CONNECTION: redis
    volumes:
      - ../../src/backend:/var/www/html
    networks:
      - exam_network
    depends_on:
      - backend

  # ===========================================
  # React Frontend
  # ===========================================
  frontend:
    build:
      context: ../../src/frontend
      dockerfile: Dockerfile
    container_name: exam_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: ${API_URL:-http://localhost:8000/api}
    volumes:
      - ../../src/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - exam_network
    depends_on:
      - backend

  # ===========================================
  # phpMyAdmin (Development)
  # ===========================================
  phpmyadmin:
    image: docker.io/library/phpmyadmin:latest
    container_name: exam_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
    ports:
      - "8080:80"
    networks:
      - exam_network
    depends_on:
      - mysql
    profiles:
      - dev

  # ===========================================
  # Nginx Reverse Proxy (Production)
  # ===========================================
  nginx:
    image: docker.io/library/nginx:alpine
    container_name: exam_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - exam_network
    depends_on:
      - backend
      - frontend
    profiles:
      - prod

# ===========================================
# Networks
# ===========================================
networks:
  exam_network:
    driver: bridge

# ===========================================
# Volumes
# ===========================================
volumes:
  mysql_data:
  redis_data:
  backend_storage:
